name: tech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^17.0.1
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.4
  flutter_riverpod: ^3.1.0
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  # -------- ASSETS --------
  assets:
    - assets/images/
    - assets/icons/

  # -------- FONTS --------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
